version: "3.8"

services:
  nginx:
    image: "nginx:stable-alpine"
    ports:
      - "8010:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/withDocker
    depends_on:
      - mysql
      - php
  php:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/withDocker
  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - "3320:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

  composer:
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/withDocker
    command: install --ignore-platform-reqs
  artisan:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/withDocker
  laravel:
    build: .
    environment:
      DB_CONNECTION: mysql
      DB_HOST: withdocker-mysql-1
      DB_PORT: 3320
      DB_DATABASE: laravel_db
      DB_USERNAME: laravel
      DB_PASSWORD: password
